name: image_gallery
description: A new Flutter project.

environment:
  sdk: '>=3.5.0 <4.0.0'  # Correct place for SDK constraint

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  flutter_staggered_grid_view: ^0.6.1
  infinite_scroll_pagination: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
